id: 8a5f5e98-d3bb-42c3-b71b-dca4b5bb0f45

name: Password Spray Response

description: >
  Automatically responds to Password Spray incidents by
  executing the Notify Security Team playbook.

enabled: true

order: 100

trigger:
  incidentTitleContains:
    - Password Spray

actions:
  - playbook: notify-teams

incident:
  severity:
    - High
    - Medium

status:
  - New